//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public string Id { get; set; }
        public string CustomerId { get; set; }
        public string RoomId { get; set; }
        public System.DateTime CheckIn { get; set; }
        public System.DateTime CheckOut { get; set; }
        public Nullable<int> AddBed { get; set; }
        public Nullable<int> AddBlanket { get; set; }
        public string AddOn { get; set; }
        public int Status { get; set; }
        public string PaymentId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual Room Room { get; set; }
    }
}
